version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80

  mysql:
    image: mysql:8.0
    restart: always
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=changthis
      - MYSQL_DATABASE=originblog
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/msyql:cached

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/backend
    environment:
      DATABASE_URL: 'mysql+pymysql://root:changthis@mysql:3306/originblog'
    depends_on:
      - mysql

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules:cached
    environment:
      - NODE_ENV=development


volumes:
  db_data:
