version: '3.7'
services:

  mysql:
    image: mysql:8.0
    container_name: db
    restart: always
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changethis
      - MYSQL_DATABASE=originblog
    volumes:
      - db_data:/var/lib/msyql:cached

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    command: python app/main.py
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/backend
    environment:
      DATABASE_URL: 'mysql://root:changthis@db:3306/originblog'
    depends_on:
      - mysql

volumes:
  db_data:
